<?php

namespace Model;

use Couchbase\Result;

class Admin extends ActiveRecord {
  protected static $tabla = 'usuarios';
  protected static $columnasDB = ['id', 'email', 'password'];

  public $id;
  public $email;
  public $password;

  public function __construct($args = [])  {
    $this->id = $args['id'] ?? null;
    $this->email = $args['email'] ?? null;
    $this->password = $args['password'] ?? null;
  }

  public function validar()
  {
    if (!$this->email){
      self::$errores['email'] = 'el email es obligatorio';
    }
    if (!$this->password){
      self::$errores['password'] = 'el password es obligatorio';
    }
    return self::$errores; // TODO: Change the autogenerated stub
  }

  public function existeUsuario() {
    //revisar que el usuario exista en la bd
    $query = "SELECT * FROM " . self::$tabla . " WHERE email = '" . $this->email . "' LIMIT 1;";

    $resultado = self::$db->query($query);

    if (!$resultado->num_rows) {
      self::$errores['usuario'] = "el usuario no existe";
      return;
    }

    return$resultado;
  }

  public function comprobarPassword($resultado) {
    $usuario = $resultado->fetch_object();

    $autenticado = password_verify($this->password, $usuario->password);

    if (!$autenticado) {
      self::$errores['usuario'] = "Correo o clave incorecta";
      return;
    }

    return $autenticado;
  }

  public function autenticar() {
    session_start();
    //llenae el arreglo se sesion
    $_SESSION['usuario'] = $this->email;
    $_SESSION['login'] = true;

    header('Location: /admin');
  }

}

